# modules/lang.py

# Словарь всех поддерживаемых языков с кодами и названиями
def get_all_languages():
    return {
        "en": "English",
        "es": "Español",
        "fr": "Français",
        "de": "Deutsch",
        "it": "Italiano",
        "pt": "Português",
        "ru": "Русский",
        "uk": "Українська",
        "pl": "Polski",
        "nl": "Nederlands",
        "ja": "日本語",
        "zh": "中文",
        "ko": "한국어",
        "ar": "العربية",
        "hi": "हिन्दी",
        "tr": "Türkçe",
        "sv": "Svenska",
        "no": "Norsk",
        "da": "Dansk",
        "fi": "Suomi",
        "cs": "Čeština",
        "el": "Ελληνικά",
        "he": "עברית",
        "ro": "Română",
        "hu": "Magyar",
        "bg": "Български",
        "sk": "Slovenčina"
    }

# Главный словарь текстов на разных языках
_texts = {
    "welcome": {
        "en": "Welcome to Surprise Me! 🎉",
        "es": "¡Bienvenido a Surprise Me! 🎉",
        "fr": "Bienvenue à Surprise Me ! 🎉",
        "de": "Willkommen bei Surprise Me! 🎉",
        "it": "Benvenuto in Surprise Me! 🎉",
        "pt": "Bem-vindo ao Surprise Me! 🎉",
        "ru": "Добро пожаловать в Surprise Me! 🎉",
        "uk": "Ласкаво просимо до Surprise Me! 🎉",
        "pl": "Witamy w Surprise Me! 🎉",
        "nl": "Welkom bij Surprise Me! 🎉",
        "ja": "Surprise Meへようこそ！🎉",
        "zh": "欢迎来到Surprise Me！🎉",
        "ko": "Surprise Me에 오신 것을 환영합니다! 🎉",
        "ar": "مرحبًا بك في Surprise Me! 🎉",
        "hi": "Surprise Me में आपका स्वागत है! 🎉",
        "tr": "Surprise Me'e hoş geldiniz! 🎉",
        "sv": "Välkommen till Surprise Me! 🎉",
        "no": "Velkommen til Surprise Me! 🎉",
        "da": "Velkommen til Surprise Me! 🎉",
        "fi": "Tervetuloa Surprise Me:en! 🎉",
        "cs": "Vítejte v Surprise Me! 🎉",
        "el": "Καλώς ήρθατε στο Surprise Me! 🎉",
        "he": "ברוכים הבאים ל-Surprise Me! 🎉",
        "ro": "Bine ai venit la Surprise Me! 🎉",
        "hu": "Üdvözlünk a Surprise Me-ben! 🎉",
        "bg": "Добре дошли в Surprise Me! 🎉",
        "sk": "Vitajte v Surprise Me! 🎉",
    },
    "surprise": {
        "en": "Surprise",
        "es": "Sorpresa",
        "fr": "Surprise",
        "de": "Überraschung",
        "it": "Sorpresa",
        "pt": "Surpresa",
        "ru": "Сюрприз",
        "uk": "Сюрприз",
        "pl": "Niespodzianka",
        "nl": "Verrassing",
        "ja": "サプライズ",
        "zh": "惊喜",
        "ko": "서프라이즈",
        "ar": "مفاجأة",
        "hi": "सरप्राइज",
        "tr": "Sürpriz",
        "sv": "Överraskning",
        "no": "Overraskelse",
        "da": "Overraskelse",
        "fi": "Yllätys",
        "cs": "Překvapení",
        "el": "Έκπληξη",
        "he": "הפתעה",
        "ro": "Surpriză",
        "hu": "Megtérés",
        "bg": "Изненада",
        "sk": "Prekvapenie",
    },
    "movie": {
        "en": "Movie",
        "es": "Película",
        "fr": "Film",
        "de": "Film",
        "it": "Film",
        "pt": "Filme",
        "ru": "Фильм",
        "uk": "Фільм",
        "pl": "Film",
        "nl": "Film",
        "ja": "映画",
        "zh": "电影",
        "ko": "영화",
        "ar": "فيلم",
        "hi": "फ़िल्म",
        "tr": "Film",
        "sv": "Film",
        "no": "Film",
        "da": "Film",
        "fi": "Elokuva",
        "cs": "Film",
        "el": "Ταινία",
        "he": "סרט",
        "ro": "Film",
        "hu": "Film",
        "bg": "Филм",
        "sk": "Film",
    },
    "music": {
        "en": "Music",
        "es": "Música",
        "fr": "Musique",
        "de": "Musik",
        "it": "Musica",
        "pt": "Música",
        "ru": "Музыка",
        "uk": "Музика",
        "pl": "Muzyka",
        "nl": "Muziek",
        "ja": "音楽",
        "zh": "音乐",
        "ko": "음악",
        "ar": "موسيقى",
        "hi": "संगीत",
        "tr": "Müzik",
        "sv": "Musik",
        "no": "Musikk",
        "da": "Musik",
        "fi": "Musiikki",
        "cs": "Hudba",
        "el": "Μουσική",
        "he": "מוסיקה",
        "ro": "Muzică",
        "hu": "Zene",
        "bg": "Музика",
        "sk": "Hudba",
    },
    "quote": {
        "en": "Quote",
        "es": "Cita",
        "fr": "Citation",
        "de": "Zitat",
        "it": "Citazione",
        "pt": "Citação",
        "ru": "Цитата",
        "uk": "Цитата",
        "pl": "Cytat",
        "nl": "Citaat",
        "ja": "引用",
        "zh": "名言",
        "ko": "인용문",
        "ar": "اقتباس",
        "hi": "उद्धरण",
        "tr": "Alıntı",
        "sv": "Citat",
        "no": "Sitat",
        "da": "Citat",
        "fi": "Lainaus",
        "cs": "Citát",
        "el": "Παραπομπή",
        "he": "ציטוט",
        "ro": "Citat",
        "hu": "Idézet",
        "bg": "Цитат",
        "sk": "Citát",
    },
    "random": {
        "en": "Random",
        "es": "Aleatorio",
        "fr": "Aléatoire",
        "de": "Zufällig",
        "it": "Casuale",
        "pt": "Aleatório",
        "ru": "Рандом",
        "uk": "Випадковий",
        "pl": "Losowy",
        "nl": "Willekeurig",
        "ja": "ランダム",
        "zh": "随机",
        "ko": "무작위",
        "ar": "عشوائي",
        "hi": "रैंडम",
        "tr": "Rastgele",
        "sv": "Slumpmässig",
        "no": "Tilfeldig",
        "da": "Tilfældig",
        "fi": "Satunnainen",
        "cs": "Náhodný",
        "el": "Τυχαίος",
        "he": "אקראי",
        "ro": "Aleatoriu",
        "hu": "Véletlenszerű",
        "bg": "Произволен",
        "sk": "Náhodný",
    },
    "recipe": {
        "en": "Recipe",
        "es": "Receta",
        "fr": "Recette",
        "de": "Rezept",
        "it": "Ricetta",
        "pt": "Receita",
        "ru": "Рецепт",
        "uk": "Рецепт",
        "pl": "Przepis",
        "nl": "Recept",
        "ja": "レシピ",
        "zh": "食谱",
        "ko": "레시피",
        "ar": "وصفة",
        "hi": "विधि",
        "tr": "Tarif",
        "sv": "Recept",
        "no": "Oppskrift",
        "da": "Opskrift",
        "fi": "Resepti",
        "cs": "Recept",
        "el": "Συνταγή",
        "he": "מתכון",
        "ro": "Rețetă",
        "hu": "Recept",
        "bg": "Рецепта",
        "sk": "Recept",
    },
    "settings": {
        "en": "Settings",
        "es": "Configuración",
        "fr": "Paramètres",
        "de": "Einstellungen",
        "it": "Impostazioni",
        "pt": "Configurações",
        "ru": "Настройки",
        "uk": "Налаштування",
        "pl": "Ustawienia",
        "nl": "Instellingen",
        "ja": "設定",
        "zh": "设置",
        "ko": "설정",
        "ar": "الإعدادات",
        "hi": "सेटिंग्स",
        "tr": "Ayarlar",
        "sv": "Inställningar",
        "no": "Innstillinger",
        "da": "Indstillinger",
        "fi": "Asetukset",
        "cs": "Nastavení",
        "el": "Ρυθμίσεις",
        "he": "הגדרות",
        "ro": "Setări",
        "hu": "Beállítások",
        "bg": "Настройки",
        "sk": "Nastavenia",
    },
    "set_lang_success": {
        "en": "Language set successfully! Please enter your local time in HH:MM format (e.g. 10:00).",
        "es": "¡Idioma configurado con éxito! Por favor, introduce tu hora local en formato HH:MM (ejemplo: 10:00).",
        "fr": "Langue définie avec succès ! Veuillez entrer votre heure locale au format HH:MM (ex: 10:00).",
        "de": "Sprache erfolgreich eingestellt! Bitte geben Sie Ihre Ortszeit im Format HH:MM ein (z.B. 10:00).",
        "it": "Lingua impostata con successo! Inserisci il tuo orario locale nel formato HH:MM (es. 10:00).",
        "pt": "Idioma definido com sucesso! Por favor, insira seu horário local no formato HH:MM (exemplo: 10:00).",
        "ru": "Язык успешно установлен! Пожалуйста, введите ваше местное время в формате ЧЧ:ММ (например, 10:00).",
       "uk": "Мову успішно встановлено! Будь ласка, введіть ваш місцевий час у форматі ГГ:ХХ (наприклад, 10:00).",
# и остальные языки...
},
"set_time_request": {
"en": "Please enter your local time in HH:MM format (e.g. 10:00) for your daily surprise.",
"es": "Por favor, ingresa tu hora local en formato HH:MM (ejemplo: 10:00) para tu sorpresa diaria.",
"fr": "Veuillez entrer votre heure locale au format HH:MM (ex: 10:00) pour votre surprise quotidienne.",
"de": "Bitte geben Sie Ihre Ortszeit im Format HH:MM ein (z.B. 10:00) für Ihre tägliche Überraschung.",
"it": "Inserisci il tuo orario locale nel formato HH:MM (es. 10:00) per la tua sorpresa quotidiana.",
"pt": "Por favor, insira seu horário local no formato HH:MM (exemplo: 10:00) para sua surpresa diária.",
"ru": "Пожалуйста, введите ваше местное время в формате ЧЧ:ММ (например, 10:00) для ежедневного сюрприза.",
"uk": "Будь ласка, введіть ваш місцевий час у форматі ГГ:ХХ (наприклад, 10:00) для щоденного сюрпризу.",
# и остальные языки...
},
"set_time_success": {
"en": "Time set successfully! You will receive your daily surprise at this time.",
"es": "¡Hora configurada con éxito! Recibirás tu sorpresa diaria a esta hora.",
"fr": "Heure définie avec succès ! Vous recevrez votre surprise quotidienne à cette heure.",
"de": "Zeit erfolgreich eingestellt! Sie erhalten Ihre tägliche Überraschung zu dieser Zeit.",
"it": "Orario impostato con successo! Riceverai la tua sorpresa quotidiana a questa ora.",
"pt": "Hora definida com sucesso! Você receberá sua surpresa diária neste horário.",
"ru": "Время успешно установлено! Вы будете получать ежедневный сюрприз в это время.",
"uk": "Час успішно встановлено! Ви отримуватимете щоденний сюрприз у цей час.",
# и остальные языки...
},
"limit_reached": {
"en": "You have reached your daily limit of requests. Please try again tomorrow.",
"es": "Has alcanzado tu límite diario de solicitudes. Por favor, inténtalo de nuevo mañana.",
"fr": "Vous avez atteint votre limite quotidienne de demandes. Veuillez réessayer demain.",
"de": "Sie haben Ihr tägliches Anfrage-Limit erreicht. Bitte versuchen Sie es morgen erneut.",
"it": "Hai raggiunto il limite giornaliero di richieste. Riprova domani.",
"pt": "Você atingiu seu limite diário de solicitações. Por favor, tente novamente amanhã.",
"ru": "Вы достигли дневного лимита запросов. Пожалуйста, попробуйте завтра.",
"uk": "Ви досягли добового ліміту запитів. Будь ласка, спробуйте завтра.",
# и остальные языки...
},
"recipe_request": {
"en": "Please enter your list of ingredients separated by commas.",
"es": "Por favor, ingresa tu lista de ingredientes separados por comas.",
"fr": "Veuillez entrer votre liste d'ingrédients séparés par des virgules.",
"de": "Bitte geben Sie Ihre Zutatenliste durch Kommas getrennt ein.",
"it": "Inserisci la tua lista di ingredienti separati da virgole.",
"pt": "Por favor, insira sua lista de ingredientes separados por vírgulas.",
"ru": "Пожалуйста, введите список ингредиентов, разделённых запятыми.",
"uk": "Будь ласка, введіть список інгредієнтів, розділених комами.",
# и остальные языки...
},
"unknown_command": {
"en": "Sorry, I didn't understand that command.",
"es": "Lo siento, no entendí ese comando.",
"fr": "Désolé, je n'ai pas compris cette commande.",
"de": "Entschuldigung, ich habe diesen Befehl nicht verstanden.",
"it": "Spiacente, non ho capito questo comando.",
"pt": "Desculpe, não entendi esse comando.",
"ru": "Извините, я не понял эту команду.",
"uk": "Вибачте, я не розумію цю команду.",
# и остальные языки...
},
}

def get_text(key: str, lang: str) -> str:
"""
Возвращает текст по ключу и языку.
Если язык не найден — возвращает английский по умолчанию.
Если ключ не найден — возвращает ключ.
"""
if key not in _texts:
return key
return _texts[key].get(lang, _texts[key].get("en", key))

---

### Как использовать

```python
from modules.lang import get_text

text = get_text("welcome", "ru")  # Добро пожаловать в Surprise Me! 🎉
