default_texts = {
    "en": {
        "menu_message": "🎁 Hi! How can I help you today?",
        "settings_button": "⚙ Settings",
        "settings_message": "⚙ What do you want to change?",
        "language_button": "🌐 Change language",
        "language_chosen": "✅ Language selected",
        "time_button": "⏰ Change time",
        "time_saved": "✅ Time saved",
        "time_format_error": "❌ Invalid time format. Please enter time as HH:MM.",
        "start_choose_time": "👋 Hi! To get daily surprises, please tell me your local time (e.g. 08:30):",
        "back_button": "🔙 Back to menu",
        "back_message": "🔙 Returning to main menu",
        "limit_reached": "⛔ You have reached your daily limit. Try again tomorrow.",
        "fallback": "🤖 I didn't understand. Use the buttons or type /start.",
        "auto_surprise_error": "❌ Error while sending auto-surprise.",
        "surprise_button": "🎁 Surprise",
        "movie_button": "🎬 Movie",
        "music_button": "🎵 Music",
        "quote_button": "💬 Quote",
        "random_button": "🎲 Random",
        "recipe_button": "🍳 Recipe",
        "ask_time_again": "⏰ Please enter your new local time (e.g. 08:30):",
    },

    "uk": {
        "menu_message": "🎁 Привіт! Як я можу вам допомогти сьогодні?",
        "settings_button": "⚙ Налаштування",
        "settings_message": "⚙ Що ви хочете змінити?",
        "language_button": "🌐 Змінити мову",
        "language_chosen": "✅ Мову вибрано",
        "time_button": "⏰ Змінити час",
        "time_saved": "✅ Час збережено",
        "time_format_error": "❌ Невірний формат часу. Введіть у форматі ГГ:ХХ.",
        "start_choose_time": "👋 Привіт! Щоб отримувати сюрпризи, скажи свій місцевий час (наприклад, 08:30):",
        "back_button": "🔙 Назад до меню",
        "back_message": "🔙 Повертаю вас у головне меню",
        "limit_reached": "⛔ Ви досягли ліміту на сьогодні. Спробуйте завтра 🙏",
        "fallback": "🤖 Не впевнений, що ви маєте на увазі. Скористайтеся кнопками або введіть /start.",
        "auto_surprise_error": "❌ Помилка при надсиланні автосюрпризу.",
        "surprise_button": "🎁 Сюрприз",
        "movie_button": "🎬 Фільм",
        "music_button": "🎵 Музика",
        "quote_button": "💬 Цитата",
        "random_button": "🎲 Рандом",
        "recipe_button": "🍳 Рецепт",
        "ask_time_again": "⏰ Вкажіть свій новий місцевий час (наприклад, 08:30):",
    },
    "pl": {
        "choose_language": "Proszę wybrać język:",
        "language_chosen": "Wybrano język: polski.",
        "greeting_and_ask_time": "Cześć! Jestem SurpriseBot. Wpisz dokładny lokalny czas (GG:MM). To potrzebne, aby wysyłać niespodzianki o 10:00 w twojej strefie czasowej.",
        "time_saved": "Czas zapisany! Użyj menu poniżej, aby otrzymać niespodzianki.",
        "menu": "🎁 Niespodzianka\n🎬 Film\n🎵 Muzyka\n💬 Cytat\n🎲 Losowy\n🍳 Przepis",
        "settings": "⚙ Ustawienia",
    },
    # и так далее для других языков…
}
