TEXTS = {
   "en": {
        "menu": "🎁 Hi! How can I help you today?",
        "settings": "⚙ Settings",
        "language_chosen": "Language selected ✅",
        "time_saved": "Time saved ✅",
        "time_format_error": "Invalid time format. Please enter time as HH:MM.",
        "limit_reached": "You have reached your daily limit. Try again tomorrow.",
        "surprise": "Surprise",
        "movie": "Movie",
        "music": "Music",
        "quote": "Quote",
        "random": "Random",
        "recipe": "Recipe",
    },
   "uk": {
        "menu": "🎁 Привіт! Як я можу вам допомогти сьогодні?",
        "settings": "⚙ Налаштування",
        "language_chosen": "Мову вибрано ✅",
        "time_saved": "Час збережено ✅",
        "time_format_error": "Невірний формат часу. Введіть у форматі ГГ:ХХ.",
        "limit_reached": "Ви досягли ліміту на сьогодні. Спробуйте завтра 🙏",
        "surprise": "Сюрприз",
        "movie": "Фільм",
        "music": "Музика",
        "quote": "Цитата",
        "random": "Рандом",
        "recipe": "Рецепт",
    },
    "pl": {
        "choose_language": "Proszę wybrać język:",
        "language_chosen": "Wybrano język: polski.",
        "greeting_and_ask_time": "Cześć! Jestem SurpriseBot. Wpisz dokładny lokalny czas (GG:MM). To potrzebne, aby wysyłać niespodzianki o 10:00 w twojej strefie czasowej.",
        "time_saved": "Czas zapisany! Użyj menu poniżej, aby otrzymać niespodzianki.",
        "menu": "🎁 Niespodzianka\n🎬 Film\n🎵 Muzyka\n💬 Cytat\n🎲 Losowy\n🍳 Przepis",
        "settings": "⚙ Ustawienia",
    },
    # и так далее для других языков…
}
