services:
  - type: web
    name: surprise-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    runtime: python

    envVars:
      - key: HUGGINGFACE_API_KEY
        value: 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
