services:
  - type: web
    name: surprise-ai-bot
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: HUGGINGFACE_API_KEY
        value: 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
