services:
  - type: web
    name: surprise-ai-bot
    env: python
    region: oregon
     plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://surprise-ai-bot.onrender.com
