services:
  - type: web
    name: surprise-ai-bot
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: WEBHOOK_URL
        sync: false
